- hosts: all
  gather_facts: true
  tasks:
    - name: Install Packages 
      apt:
        name: "{{ item  }}"
        state: present
        update_cache: yes 
      with_items: 
        - nginx
        - python3
        - ufw 
      when: ansible_distribution in ['Debian', 'Ubuntu']
    
    - name: Install Packages for 
      yum:
        name: "{{ item  }}"
        state: present
        update_cache: yes 
      with_items: 
        - nginx
        - python3 
      when: ansible_distribution in ['CentOS', 'RedHat']

    